# Generated by Django 3.0.7 on 2020-06-08 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rectangle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=20)),
                ('height', models.IntegerField(default=20)),
            ],
        ),
        migrations.AddField(
            model_name='pixel',
            name='rect',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pixel.Rectangle'),
        ),
    ]
